version: "3"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    env_file:
      - services.env

  flight:
    container_name: flight-service
    build: ./flight-service
    restart: always
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
    ports:
      - "8080:80"
    env_file:
      - services.env

  payment:
    container_name: payment-service
    build: ./payment-service
    restart: always
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
    ports:
      - "8090:80"
    env_file:
      - services.env

  push:
    container_name: push-service
    build: ./push-service
    restart: always
    ports:
      - "8100:80"
    env_file:
      - services.env

  countries:
    container_name: countries-service
    build: ./countries-service
    restart: always
    ports:
      - "8110:80"
    env_file:
      - services.env

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - /mongo/data:/data/db
    ports:
      - "27017:27017"
