version: "3"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    env_file:
      - services.env

  flight:
    container_name: flight-service
    build: ./flight-service
    restart: always
    depends_on:
      - auth
    ports:
      - "8080:80"
    env_file:
      - services.env
    volumes:
      - ./auth-service/keys/:/code/keys/

  payment:
    container_name: payment-service
    build: ./payment-service
    restart: always
    depends_on:
      - auth
    ports:
      - "8090:80"
    env_file:
      - services.env
    volumes:
      - ./auth-service/keys/:/code/keys/

  countries:
    container_name: countries-service
    build: ./countries-service
    restart: always
    depends_on:
      - auth
    ports:
      - "8110:80"
    env_file:
      - services.env
    volumes:
      - ./auth-service/keys/:/code/keys/

  auth:
    container_name: auth-service
    build: ./auth-service
    ports:
      - "8120:80"
    env_file:
      - services.env
    volumes:
      - ./auth-service/keys:/code/keys

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"